// app/layout.tsx
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions"; 
import { Poppins } from "next/font/google";
import "./globals.css"; // Ensure global styles are imported
import Headertop from "@/components/menu/Headertop";
import { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import HeaderBottom from "@/components/menu/Headerbottom";
import Header from "@/components/menu/Header";
import Footer from "@/components/menu/Footer";
import  StoreProvider  from "@/components/StoreProvider";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "e-commerce app",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  // Fetch the session server-side
  const session = await getServerSession(authOptions);

  return (
  
      <html lang="en">
        <body className={poppins.className}>
        <StoreProvider>
              <Headertop />
              <Header/>
              <HeaderBottom />
              {children}  <Footer /></StoreProvider>

        </body>
      </html>
    
  );
};

export default RootLayout;
